AllCops:
  Exclude:
    - 'ares.gemspec'
    - 'spec/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 89

Documentation:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false
